name: Minecraft version request
description: Request support for a specific Minecraft version
title: "[MC version request] Add support for <version>"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please make sure that the missing mapping has not already been reported in another issue.
        If more than one mapping is missing, please submit one separate issue for each.
  - type: text
    id: version
    attributes:
      label: Minecraft version
      description: What Minecraft version are you requesting support for?
    validations:
      required: true
