name: Missing mapping
description: Report missing or outdated mapping for a biome
title: "[Missing mapping] Mapping for <biome> is missing"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please make sure that the missing mapping has not already been reported in another issue.
        If more than one mapping is missing, please submit one separate issue for each.
   - type: textarea
    id: description
    attributes:
      label: Description
      description: Add any context or screenshots below.
    validations:
      required: true
  - type: dropdown
    id: versions
    attributes:
      label: Game version
      description: What game versions are affected? Select all applicable game versions. Active support for mods is limited to the latest 3 major versions.
      multiple: false
      options:
        - "1.21.4"
        - "1.21.3"
        - "1.21"
        - "1.20.4"
        - "1.20.3"
        - "1.20.2"
        - "1.20.1"
        - "1.20"
        - "Not listed"
    validations:
      required: true
